apiVersion: apps/v1
kind: Deployment 
metadata:
  name: deployment-nginx
  namespace: web
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: 
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 637423339404.dkr.ecr.us-east-2.amazonaws.com/nginx:latest
        ports:
        - containerPort: 80
