apiVersion: apps/v1
kind: Deployment 
metadata:
  name: deployment-http
  namespace: web
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: http 
  template:
    metadata: 
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: 637423339404.dkr.ecr.us-east-2.amazonaws.com/http:latest
        ports:
        - containerPort: 80
