apiVersion: apps/v1
kind: Deployment 
metadata:
  name: deployment-http
  namespace: web
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: http 
  template:
    metadata: 
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: "${{ secrets.ECR_HTTP_REPO }}:latest"
        ports:
        - containerPort: 80
