name: EKS Deployment 

on: 
  workflow_run:
    workflows: ["Build and Push Docker Images to ECR"]
    types: 
      - completed

jobs:
  k8deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: clone repo 
      uses: actions/checkout@v2

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1 
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESSKEY_LIAM}}
        aws-secret-access-key: ${{ secrets.AWS_SECRETKEY_LIAM}}
        aws-region: us-east-2

    - name: update kubeconfig
      run: aws eks update-kubeconfig --name manualcluster1 --region us-east-2

    - name: create namespace
      run: kubectl create namespace web

    - name: Apply Deployment 
      run: kubectl apply -f deployment-http.yaml
      working-directory: Kubernetes/http

    - name: Apply Service
      run: kubectl apply -f loadbalancer.yaml
      working-directory: Kubernetes/http

    - name: Apply Deployment 
      run: kubectl apply -f deployment-nginx.yaml
      working-directory: Kubernetes/nginx

    - name: Apply Service
      run: kubectl apply -f loadbalancer.yaml
      working-directory: Kubernetes/nginx